server:
  port: 8181

spring:
  application:
    name: project
  logging:
    level:
      org.springframework.core.env: DEBUG
      org.springframework.data.redis: DEBUG
      org.springframework.boot.context.config: DEBUG

  datasource:
    url: jdbc:mariadb://localhost:3306/project_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:3600000}