server:
  port: 8181

spring:
  application:
    name: project
  logging:
    level:
      org.springframework.core.env: DEBUG
      org.springframework.data.redis: DEBUG
      org.springframework.boot.context.config: DEBUG

  datasource:
    url: jdbc:mariadb://localhost:3306/project_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      connect-timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 200ms

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET:khinhungdinhnuikhongcongoccanhnuakhisongdangungchaytualua}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:360000000}

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    org.springframework.boot.autoconfigure.data.redis: DEBUG