server:
  port: 8181

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/project_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: redis
    port: 6379

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:3600000}
