spring:
  redis:
    host: redis
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    connect-timeout: 60000

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - DOCKER-PROFILE-ACTIVE: %msg%n"